version: '3.8'

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../backend:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../backend:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: dmitryk414@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/node/Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  db_data:
